-- CreateTable
CREATE TABLE `compra` (
    `ID_COMPRA_I` INTEGER NOT NULL AUTO_INCREMENT,
    `CLIENTE_DNI_I` CHAR(8) NOT NULL,
    `DESCRIPTION_COMPRA_V` TEXT NULL,
    `PRECIO_TOTAL_D` DECIMAL(10, 2) NULL,
    `ESTADO_B` BOOLEAN NULL DEFAULT (true),
    `FECHA_CREATE_D` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `FECHA_UPDATE_D` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `FK_cliente_dni`(`CLIENTE_DNI_I`),
    PRIMARY KEY (`ID_COMPRA_I`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `compra_producto` (
    `ID_COMPRA_PRODUCTO_I` INTEGER NOT NULL AUTO_INCREMENT,
    `COMPRA_ID_I` INTEGER NOT NULL,
    `PRODUCTO_ID_I` INTEGER NOT NULL,
    `NAME_PRO_V` TEXT NOT NULL,
    `PRECIO_COMPRA_D` DECIMAL(10, 2) NOT NULL,
    `ESTADO_B` BOOLEAN NULL DEFAULT (true),
    `FECHA_CREATE_D` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `FECHA_UPDATE_D` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `FK_compra_pro`(`COMPRA_ID_I`),
    INDEX `FK_producto_pro`(`PRODUCTO_ID_I`),
    PRIMARY KEY (`ID_COMPRA_PRODUCTO_I`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `producto` (
    `ID_PRODUCTO_I` INTEGER NOT NULL AUTO_INCREMENT,
    `TITLE_V` VARCHAR(255) NOT NULL,
    `DESCRIPTION_V` TEXT NOT NULL,
    `PRECIO_D` DECIMAL(10, 2) NOT NULL,
    `URL_FILE_T` TEXT NOT NULL,
    `ESTADO_B` BOOLEAN NULL DEFAULT (true),
    `FECHA_CREATE_D` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `FECHA_UPDATE_D` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `CANTIDAD_STOCK` INTEGER UNSIGNED NULL DEFAULT 0,

    PRIMARY KEY (`ID_PRODUCTO_I`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `usuario` (
    `ID_DNI_C` CHAR(8) NOT NULL,
    `AP_PATERNO_V` VARCHAR(50) NULL,
    `AP_MATERNO_V` VARCHAR(50) NULL,
    `NOMBRE_V` VARCHAR(100) NULL,
    `CORREO_V` VARCHAR(200) NOT NULL,
    `PASSWORD_V` VARCHAR(255) NOT NULL,
    `FOTO_V` VARCHAR(100) NULL DEFAULT ('user.png'),
    `ESTADO_B` BOOLEAN NULL DEFAULT (true),

    PRIMARY KEY (`ID_DNI_C`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `compra` ADD CONSTRAINT `FK_cliente_dni` FOREIGN KEY (`CLIENTE_DNI_I`) REFERENCES `usuario`(`ID_DNI_C`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `compra_producto` ADD CONSTRAINT `FK_compra_pro` FOREIGN KEY (`COMPRA_ID_I`) REFERENCES `compra`(`ID_COMPRA_I`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `compra_producto` ADD CONSTRAINT `FK_producto_pro` FOREIGN KEY (`PRODUCTO_ID_I`) REFERENCES `producto`(`ID_PRODUCTO_I`) ON DELETE CASCADE ON UPDATE CASCADE;
